# Lets run on the new infrastructure
sudo: false

language: python
python:
  - "2.7"

install:
  - pip install tox

# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
#   - mkdir geckodriver
#   - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
#   - export PATH=$PATH:$PWD/geckodriver
#   - sleep 1 # give xvfb some time to start

script:
  - ./scripts/prepare_server.sh
  - ./scripts/start_server.sh
#  - SELENIUM_DRIVER="selenium.webdriver.Firefox" tox -e docs-strict
  - tox -e docs-strict

after_script:
  - ./scripts/teardown_server.sh
  - export PUBLISH_REPO=$([ "$TRAVIS_BRANCH" = "publish" ] && echo "aristotle-mdr/published-documentation" || echo "aristotle-mdr/user-documentation")
  - echo $TRAVIS_BRANCH
  - echo $PUBLISH_REPO

after_failure:
  - cat server.log

deploy:
  provider: pages
  local_dir: docs/_build/html
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: draft
